ribbon:
  ConnectTimeout: 1000 # 服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 # 服务请求处理超时时间（毫秒）
  OkToRetryOnAllOperations: true # 对超时请求启用重试机制
  MaxAutoRetriesNextServer: 1 # 切换重试实例的最大个数
  MaxAutoRetries: 1 # 切换实例后重试最大次数
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 修改负载均衡算法
  eager-load: # 提前加载指定服务节点信息
    enabled: true # 启用
    clients: mock-user-service # 指定服务名

service-url:
  user-service: http://mock-user-service